
USE [master]
GO

/****** Object:  Database [game100by1]    Script Date: 17.02.2023 20:43:09 ******/
CREATE DATABASE [game100by1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'game100by1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\game100by1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'game100by1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\game100by1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [game100by1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [game100by1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [game100by1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [game100by1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [game100by1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [game100by1] SET ARITHABORT OFF 
GO

ALTER DATABASE [game100by1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [game100by1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [game100by1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [game100by1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [game100by1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [game100by1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [game100by1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [game100by1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [game100by1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [game100by1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [game100by1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [game100by1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [game100by1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [game100by1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [game100by1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [game100by1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [game100by1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [game100by1] SET RECOVERY FULL 
GO

ALTER DATABASE [game100by1] SET  MULTI_USER 
GO

ALTER DATABASE [game100by1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [game100by1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [game100by1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [game100by1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [game100by1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [game100by1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [game100by1] SET QUERY_STORE = OFF
GO

ALTER DATABASE [game100by1] SET  READ_WRITE 
GO

USE [game100by1]
GO

/****** Object:  Table [dbo].[Questions]    Script Date: 17.02.2023 20:44:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Questions](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[text] [nvarchar](max) NULL,
 CONSTRAINT [PK_Questions] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

USE [game100by1]
GO

/****** Object:  Table [dbo].[Player]    Script Date: 17.02.2023 20:44:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Player](
	[login] [nchar](10) NOT NULL,
	[password] [nvarchar](max) NOT NULL,
	[money] [int] NOT NULL,
	[level] [int] NOT NULL,
	[name] [nvarchar](max) NULL,
	[profile] [nvarchar](max) NULL,
 CONSTRAINT [PK_Player] PRIMARY KEY CLUSTERED 
(
	[login] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


USE [game100by1]
GO

/****** Object:  Table [dbo].[Answers]    Script Date: 17.02.2023 20:45:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Answers](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_question] [int] NOT NULL,
	[variant] [nvarchar](50) NOT NULL,
	[order] [int] NOT NULL,
	[cnt] [int] NULL,
 CONSTRAINT [PK_Answers] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Answers]  WITH CHECK ADD  CONSTRAINT [FK_Answers_Questions] FOREIGN KEY([id_question])
REFERENCES [dbo].[Questions] ([id])
GO

ALTER TABLE [dbo].[Answers] CHECK CONSTRAINT [FK_Answers_Questions]
GO
